update pull_request.yml to wait and check build result

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -10,15 +10,94 @@ on:
       - synchronize
       - reopened
   workflow_dispatch:   # cho phép bấm chạy tay
+    inputs:
+      branch:
+        description: "Branch to run"
+        type: string
+        required: true
+        default: "feature"
+      suite:
+        description: "Test suite to run"
+        type: string
+        required: true
+        default: "smoke_test"
 
 jobs:
   trigger:
     runs-on: ubuntu-latest
     steps:
       - name: Trigger Jenkins Job
+        env:
+          JENKINS_USER: ${{ vars.JENKINS_USER }}
+          JENKINS_API_TOKEN: ${{ vars.JENKINS_API_TOKEN }}
+          JENKINS_BASE_URL: ${{ vars.JENKINS_URL }}
+          JENKINS_JOB: ${{ vars.JENKINS_JOB }}
+          BRANCH: ${{ inputs.branch }}
+          SUITE: ${{ inputs.suite }}
+
+        shell: bash
         run: |
-          curl -X POST "${{ vars.JENKINS_URL}}/job/${{ vars.JENKINS_JOB }}/buildWithParameters" \
-            --user "${{ vars.JENKINS_USER }}:${{ vars.JENKINS_TOKEN }}" \
-            --data-urlencode "BRANCH=feature" \
-            --data-urlencode "SUITE=smoke_test"
-        # nothing 1
+          set -euo pipefail
+          AUTH="${JENKINS_USER}:${JENKINS_API_TOKEN}"
+
+        # 1. Trigger jenkins job
+           RESP_QUEUE="$(curl -sS -X POST \
+           "${JENKINS_BASE_URL}/job/${JENKINS_JOB}/buildWithParameters" \
+           --user "$AUTH" \
+           --data-urlencode "BRANCH=${BRANCH}" \
+           --data-urlencode "SUITE=${SUITE}" \
+           -D - -o /dev/null)"
+  
+            QUEUE_URL="$(echo "$RESP_QUEUE" | awk 'BEGIN{IGNORECASE=1} /^location:/{print $2}' | tr -d '\r')"
+            echo "QUEUE_URL=$QUEUE_URL"
+            QUEUE_API="${QUEUE_URL}api/json?tree=executable%5Bnumber,url%5D"
+               
+            RESP=""
+            for i in {1..300}; do
+              RESP="$(curl -sS "$QUEUE_API" --user "$AUTH")"
+              echo "QUEUE_API_RESP=$RESP"
+              
+              BUILD_URL="$(echo "$RESP" | jq -r '.executable.url // empty')"
+                 
+            # Kiểm tra nếu có dữ liệu thì break
+              if [[ -n "$BUILD_URL" ]]; then
+                break
+              fi
+              
+              sleep 1
+            done
+            
+          # Kiểm tra nếu undefined hoặc empty string thì báo lỗi
+            if [[ -z "${BUILD_URL:-}" ]]; then
+              echo "ERROR: timed out waiting for executable URL from queue"
+              exit 1
+            fi
+               
+            BUILD_API="${BUILD_URL}api/json"
+          # 3) Poll build until result != null
+            for i in {1..900}; do
+              BUILD_RESP="$(curl -sS "$BUILD_API" --user "$AUTH")"
+              echo "BUILD_RESP=$BUILD_RESP"
+              
+              RESULT="$(echo "$BUILD_RESP" | jq -r '.result // empty')"
+              if [[ -n "$RESULT" ]]; then
+                echo "FINAL_RESULT=$RESULT"
+                break
+              fi  
+               
+              sleep 1
+            done
+               
+            if [[ -z "${RESULT:-}" ]]; then
+              echo "ERROR: timed out waiting for build result"
+              exit 1
+            fi
+
+          # 4) Fail workflow if Jenkins build failed
+               if [[ "$RESULT" != "SUCCESS" ]]; then
+                  echo "Jenkins build failed: $RESULT"
+                  exit 1
+               fi
+               
+               echo "Jenkins build success."
+
